### ISSUE TITLE
Email Privacy

### ISSUE THREAD

**Issue by U8NWXD** [alanefl/culturemesh-api#44]
User emails should be kept private as they can identify user's real-world identities, which could expose members of certain groups to persecution. Therefore a user's email address should only be revealed via authenticated requests and to the user to whom the address belongs. This requires the following changes:
* GET `/user/users`: Email should not be present in the user objects returned
* GET `/user/{userId}`: Email should not be present in the user objects returned
* GET `/user/email`: Should not exist. Instead, return the user ID or user object along with token
in GET `/account/token`

As another consideration, rejecting account creation due to duplicated email allows someone to determine whether a given email address is associated with a CultureMesh account. If there is a situation in which just having a CultureMesh account could lead to persecution, this would be cause for concern. A possible remedy would be to make the user click a link in a confirmation email prior to activating an account or allowing login. That way, even in the case of a duplicate email address, we can display a message to check for a verification email (even though no such email will be sent), making the cases of an account existing and not existing result in identical behavior during account creation.

**Comment by alanefl** [comment]
Good issue. Regarding email rejection at login, another option is simply to say that either the password or email are incorrect.  

This doesn't give anyone any information about whether an email address is registered in the site, and it demands less steps from the users than if we were to require them to do email verification.

**Comment by DrewGregory** [comment]
If they are creating an account, then it would be impossible to have an "incorrect" password. @U8NWXD brought up never throwing an error when they are making an account due to a redundant email, as someone could then deduce that an email is registered on CultureMesh if they are unable to register that email themselves on CultureMesh.

**Comment by alanefl** [comment]
Ahh I see.  Makes sense.  Let's keep this as the TODO then
